### ISSUE TITLE
Erro na leitura da midia 3459

### ISSUE THREAD

**Issue by DeCastro13** [DisciplinasProgramacao/poo_tp_manha-grupo-llli#1]
A mídia com o Id 3459, é a primeira mídia do Arquivo POO_Serie.csv. Eu acredito que por algum motivo ele não considera 3459 como um int. 
Anteriormente estava recebendo o erro "java.lang.NumberFormatException"  entao criei o " 
if (idMidia.matches("-?\\d+")) this.idMidia = Integer.valueOf(idMidia);" na linha 60 da classe midia que so ira permitir definir um id se o IdMIdia informado apenas conter números.
Vale destacar que apenas essa mídia está dando esse erro.

**Comment by joaocaram** [comment]
@joaocaram  verificar a issue do @DeCastro13

**Comment by joaocaram** [comment]
@DeCastro13 De fato, este problema está "solucionado" em uma das especificações posteriores (acho que é a que fala do Filme). A primeira linha de cada arquivo de dados deve conter um cabeçalho do formato e deve ser ignorada pela leitura.
